[dependencies]
lazy_static = { version = "1.4", features = ["spin_no_std"] }
lock = { git = "https://github.com/DeathWish5/kernel-sync", rev = "8486b8" }
trapframe = "0.9.0"
riscv-decode = { git = "https://github.com/latte-c/riscv-decode", rev = "bc8da4e" }
